apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: encryptify-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Day-fit/Encryptify-CD.git
    targetRevision: HEAD
    path: ArgoCD-Configuration
    helm:
      releaseName: encryptify-app-of-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
