apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: encryptify-app-config
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: oci-secret-store
    kind: ClusterSecretStore
  target:
    name: encryptify-app-config
    creationPolicy: Owner
  data:
    - remoteRef:
        key: "encryptify-app-config"
        property: DB_USERNAME
      secretKey: DB_USERNAME
    - remoteRef:
        key: "encryptify-app-config"
        property: DB_PASSWORD
      secretKey: DB_PASSWORD
    - remoteRef:
        key: "encryptify-app-config"
        property: DB_HOST
      secretKey: DB_HOST
    - remoteRef:
        key: "encryptify-app-config"
        property: DB_NAME
      secretKey: DB_NAME

    - remoteRef:
        key: "encryptify-app-config"
        property: REDIS_PASSWORD
      secretKey: REDIS_PASSWORD
    - remoteRef:
        key: "encryptify-app-config"
        property: REDIS_HOST
      secretKey: REDIS_HOST

    - remoteRef:
        key: "encryptify-app-config"
        property: RABBITMQ_USER
      secretKey: RABBITMQ_USER
    - remoteRef:
        key: "encryptify-app-config"
        property: RABBITMQ_PASSWORD
      secretKey: RABBITMQ_PASSWORD
    - remoteRef:
        key: "encryptify-app-config"
        property: RABBITMQ_HOST
      secretKey: RABBITMQ_HOST
    - remoteRef:
        key: "encryptify-app-config"
        property: RABBITMQ_STATS_STREAM
      secretKey: RABBITMQ_STATS_STREAM

    - remoteRef:
        key: "encryptify-app-config"
        property: ALLOWED_ORIGINS_PATTERNS
      secretKey: ALLOWED_ORIGINS_PATTERNS

    - remoteRef:
        key: "encryptify-app-config"
        property: MAIL_USERNAME
      secretKey: MAIL_USERNAME
    - remoteRef:
        key: "encryptify-app-config"
        property: MAIL_PASSWORD
      secretKey: MAIL_PASSWORD
    - remoteRef:
        key: "encryptify-app-config"
        property: MAIL_HOST
      secretKey: MAIL_HOST
    - remoteRef:
        key: "encryptify-app-config"
        property: MAIL_PORT
      secretKey: MAIL_PORT
    - remoteRef:
        key: "encryptify-app-config"
        property: MAIL_FROM
      secretKey: MAIL_FROM

    - remoteRef:
        key: "encryptify-app-config"
        property: ENCRYPTIFY_DOMAIN
      secretKey: ENCRYPTIFY_DOMAIN

    - remoteRef:
        key: "encryptify-app-config"
        property: JWKS_URI
      secretKey: JWKS_URI

    - remoteRef:
        key: "encryptify-app-config"
        property: MINIO_USERNAME
      secretKey: MINIO_USERNAME
    - remoteRef:
        key: "encryptify-app-config"
        property: MINIO_PASSWORD
      secretKey: MINIO_PASSWORD
    - remoteRef:
        key: "encryptify-app-config"
        property: MINIO_URL
      secretKey: MINIO_URL